export namespace GoalInstructions {
  export function timed(text: string) {
    // The time-based event must be the object of "wait for" ("wait for the
    // deploy"). A passing mention inside 80 chars, such as "wait for the
    // reviewer to approve, then fix the build", must not curb the goal and hide
    // the read/edit/bash tools the work needs. A word boundary after the event
    // keeps "builder" and "buildings" from matching "build" while still counting
    // "deployment" and "builds".
    return /\bwait for (?:the |a |an |my |our )?(?:deploy(?:ment)?s?|builds?|ci)\b/i.test(text)
  }

  export const help =
    "Use /goal <objective> to keep working toward a goal in this session. Complete means reported by the working model, not independently verified. The model uses goal_report to report completion or a blocker with a reason. No progress without an explicit report, or errors, pause the goal. /goal pause stops, /goal resume continues (or restarts a complete goal), and /goal clear explicitly removes the saved objective and reason. Stop or /goal pause stops active work; a new message is handled first, then the goal continues. Active goals become paused after a backend restart; complete goals stay complete. Waiting on time is a normal goal action: a scheduled wakeup, a cron task, or a background-process wait suspends the goal until it fires, and the goal shows as waiting while it waits. Do not report a time-based wait as blocked; schedule the wait and let the goal resume itself. If this goal is to wait for a deploy, build, CI job, or other time-based event, your first tool call must be schedule_wakeup, cron_create, or background_process. Do not explore the repository, search for a deploy, or poll instead of scheduling. Do not report blocked because no deploy is visible; schedule the wait anyway. The caps are at most 10 pending wakeups (MAX_PER_SESSION), 10 cron tasks (MAX_CRON_PER_SESSION), and the 7-day horizon, which clamps a longer wait and says so in the tool result. Completing, blocking, pausing, or clearing a goal cancels its armed wakeups and cron tasks."

  export function prompt(text: string) {
    return `If this goal is to wait for a deploy, build, CI job, or other time-based event, your first tool call must be schedule_wakeup, cron_create, or background_process. Do not explore the repository, search for a deploy, or poll instead of scheduling. Do not report blocked because no deploy is visible; schedule the wait anyway.\n\nContinue working toward this session goal:\n\n${text}\n\nUse the existing conversation and take the next useful step. Proceed autonomously with safe, reversible decisions instead of asking clarification questions. The question tool is unavailable during active goal execution, including delegated work. Do not repeat completed work or status-only reports. Waiting on time is a normal goal action: a scheduled wakeup, a cron task, or a non-terminal background process suspends the goal until it fires or exits, and the goal shows as waiting until then; no further goal turn runs in between. Do not report a time-based wait as blocked; report blocked only when no scheduled wait can help. The caps are at most 10 pending wakeups (MAX_PER_SESSION), 10 cron tasks (MAX_CRON_PER_SESSION), and the 7-day horizon, which clamps a longer wait and says so in the tool result. Completing, blocking, pausing, or clearing the goal cancels its armed wakeups and cron tasks. If the goal is met, call goal_report with status complete and a concrete reason, then give your final response. If a genuine blocker prevents safe progress, call goal_report with status blocked and the blocker reason, then stop instead of asking the user. Only the root Goal worker can call goal_report; delegated workers must return their findings to the root. Completion is your report, not independent verification. Keep all existing permission and scope limits.`
  }
}
