import { Config } from "effect"
import { InstallationChannel } from "../installation/version"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

const UNSTABLE_CHANNELS = new Set(["dev", "beta", "local"])
function unstableDefault(key: string) {
  return truthy(key) || (!falsy(key) && UNSTABLE_CHANNELS.has(InstallationChannel))
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const HARNESS_EXPERIMENTAL = truthy("HARNESS_EXPERIMENTAL")
const HARNESS_DISABLE_CLAUDE_CODE = truthy("HARNESS_DISABLE_CLAUDE_CODE")
const HARNESS_DISABLE_CLAUDE_CODE_SKILLS = HARNESS_DISABLE_CLAUDE_CODE || truthy("HARNESS_DISABLE_CLAUDE_CODE_SKILLS")
const copy = process.env["HARNESS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["HARNESS_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("HARNESS_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  HARNESS_AUTO_SHARE: truthy("HARNESS_AUTO_SHARE"),
  HARNESS_AUTO_HEAP_SNAPSHOT: truthy("HARNESS_AUTO_HEAP_SNAPSHOT"),
  HARNESS_GIT_BASH_PATH: process.env["HARNESS_GIT_BASH_PATH"],
  HARNESS_CONFIG: process.env["HARNESS_CONFIG"],
  HARNESS_CONFIG_CONTENT: process.env["HARNESS_CONFIG_CONTENT"],
  HARNESS_DISABLE_AUTOUPDATE: truthy("HARNESS_DISABLE_AUTOUPDATE"),
  HARNESS_ALWAYS_NOTIFY_UPDATE: truthy("HARNESS_ALWAYS_NOTIFY_UPDATE"),
  HARNESS_DISABLE_PRUNE: truthy("HARNESS_DISABLE_PRUNE"),
  HARNESS_DISABLE_TERMINAL_TITLE: truthy("HARNESS_DISABLE_TERMINAL_TITLE"),
  HARNESS_SHOW_TTFD: truthy("HARNESS_SHOW_TTFD"),
  HARNESS_DISABLE_DEFAULT_PLUGINS: truthy("HARNESS_DISABLE_DEFAULT_PLUGINS"),
  HARNESS_DISABLE_LSP_DOWNLOAD: truthy("HARNESS_DISABLE_LSP_DOWNLOAD"),
  HARNESS_ENABLE_EXPERIMENTAL_MODELS: truthy("HARNESS_ENABLE_EXPERIMENTAL_MODELS"),
  HARNESS_DISABLE_AUTOCOMPACT: truthy("HARNESS_DISABLE_AUTOCOMPACT"),
  HARNESS_DISABLE_MODELS_FETCH: truthy("HARNESS_DISABLE_MODELS_FETCH"),
  HARNESS_DISABLE_MOUSE: truthy("HARNESS_DISABLE_MOUSE"),
  HARNESS_DISABLE_CLAUDE_CODE,
  HARNESS_DISABLE_CLAUDE_CODE_PROMPT: HARNESS_DISABLE_CLAUDE_CODE || truthy("HARNESS_DISABLE_CLAUDE_CODE_PROMPT"),
  HARNESS_DISABLE_CLAUDE_CODE_SKILLS,
  HARNESS_DISABLE_EXTERNAL_SKILLS: truthy("HARNESS_DISABLE_EXTERNAL_SKILLS"),
  HARNESS_EXPERIMENTAL_CUSTOMIZE_SKILL: unstableDefault("HARNESS_EXPERIMENTAL_CUSTOMIZE_SKILL"),
  HARNESS_FAKE_VCS: process.env["HARNESS_FAKE_VCS"],
  HARNESS_SERVER_PASSWORD: process.env["HARNESS_SERVER_PASSWORD"],
  HARNESS_SERVER_USERNAME: process.env["HARNESS_SERVER_USERNAME"],
  HARNESS_ENABLE_QUESTION_TOOL: truthy("HARNESS_ENABLE_QUESTION_TOOL"),

  HARNESS_EXPERIMENTAL,

  HARNESS_EXPERIMENTAL_CLAUDE_MIGRATION: truthy("HARNESS_EXPERIMENTAL_CLAUDE_MIGRATION"),

  HARNESS_EXPERIMENTAL_FILEWATCHER: Config.boolean("HARNESS_EXPERIMENTAL_FILEWATCHER").pipe(Config.withDefault(false)),

  HARNESS_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("HARNESS_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),

  HARNESS_EXPERIMENTAL_ICON_DISCOVERY: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_ICON_DISCOVERY"),

  HARNESS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("HARNESS_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),

  HARNESS_ENABLE_EXA: truthy("HARNESS_ENABLE_EXA") || HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_EXA"),

  HARNESS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("HARNESS_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),

  HARNESS_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("HARNESS_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),

  HARNESS_EXPERIMENTAL_OXFMT: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_OXFMT"),

  HARNESS_EXPERIMENTAL_LSP_TY: truthy("HARNESS_EXPERIMENTAL_LSP_TY"),

  HARNESS_EXPERIMENTAL_LSP_TOOL: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_LSP_TOOL"),

  HARNESS_EXPERIMENTAL_SCOUT: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_SCOUT"),

  HARNESS_EXPERIMENTAL_MARKDOWN: !falsy("HARNESS_EXPERIMENTAL_MARKDOWN"),

  HARNESS_ENABLE_PARALLEL: truthy("HARNESS_ENABLE_PARALLEL") || truthy("HARNESS_EXPERIMENTAL_PARALLEL"),

  HARNESS_MODELS_URL: process.env["HARNESS_MODELS_URL"],

  HARNESS_MODELS_PATH: process.env["HARNESS_MODELS_PATH"],

  HARNESS_DISABLE_EMBEDDED_WEB_UI: truthy("HARNESS_DISABLE_EMBEDDED_WEB_UI"),

  HARNESS_DB: process.env["HARNESS_DB"],

  HARNESS_DISABLE_CHANNEL_DB: truthy("HARNESS_DISABLE_CHANNEL_DB"),

  HARNESS_SKIP_MIGRATIONS: truthy("HARNESS_SKIP_MIGRATIONS"),

  HARNESS_STRICT_CONFIG_DEPS: truthy("HARNESS_STRICT_CONFIG_DEPS"),

  HARNESS_WORKSPACE_ID: process.env["HARNESS_WORKSPACE_ID"],

  HARNESS_EXPERIMENTAL_WORKSPACES: enabledByExperimental("HARNESS_EXPERIMENTAL_WORKSPACES"),

  HARNESS_EXPERIMENTAL_EVENT_SYSTEM: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_EVENT_SYSTEM"),

  HARNESS_EXPERIMENTAL_SESSION_SWITCHING: HARNESS_EXPERIMENTAL || truthy("HARNESS_EXPERIMENTAL_SESSION_SWITCHING"),

  HARNESS_EXPERIMENTAL_SESSION_SWITCHER: enabledByExperimental("HARNESS_EXPERIMENTAL_SESSION_SWITCHER"),

  HARNESS_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("HARNESS_DISABLE_FFF"),

  get HARNESS_DISABLE_PROJECT_CONFIG() {
    return truthy("HARNESS_DISABLE_PROJECT_CONFIG")
  },
  get HARNESS_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("HARNESS_EXPERIMENTAL_REFERENCES")
  },
  get HARNESS_TUI_CONFIG() {
    return process.env["HARNESS_TUI_CONFIG"]
  },
  get HARNESS_CONFIG_DIR() {
    return process.env["HARNESS_CONFIG_DIR"]
  },
  get HARNESS_PURE() {
    return truthy("HARNESS_PURE")
  },
  get HARNESS_PERMISSION() {
    return process.env["HARNESS_PERMISSION"]
  },
  get HARNESS_PLUGIN_META_FILE() {
    return process.env["HARNESS_PLUGIN_META_FILE"]
  },
  get HARNESS_CLIENT() {
    return process.env["HARNESS_CLIENT"] ?? "cli"
  },
  get HARNESS_SESSION_RETRY_LIMIT() {
    return number("HARNESS_SESSION_RETRY_LIMIT")
  },
}
